import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { GoogleGenerativeAI } from '@google/generative-ai';
import puppeteer from 'puppeteer';
import crypto from 'crypto';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.send('SEBRI Backend API is live! Use the frontend to interact with it.');
});

const PORT = process.env.PORT || 5000;

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || 'YOUR_KEY_HERE');

// Utility for hashing
const generateHash = (data) => {
  return crypto.createHash('sha256').update(data).digest('hex');
};

import path from 'path';
import fs from 'fs';

const __dirname = path.resolve();
const referencePath = path.join(__dirname, 'reference_agreement.md');
const GOLD_STANDARD_REFERENCE = fs.readFileSync(referencePath, 'utf-8');

app.post('/api/generate-agreement', async (req, res) => {
  try {
    const { formData } = req.body;
    
    // 1. Prepare Prompt
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = `
      System: You are a senior real estate attorney in India. Generate a FULL, ELABORATE, COURT-READY rental agreement.
      Reference Model (Follow this structure, tone, and numbering exactly):
      ${GOLD_STANDARD_REFERENCE}
      
      User Data to Mapping:
      ${JSON.stringify(formData, null, 2)}
      
      Output Requirements:
      - Return the FINAL agreement in clean HTML format.
      - Use <h1> for the title "RENTAL AGREEMENT".
      - Use <h3> for numbered sections (e.g., 1. RENT).
      - Use <p> for legal clauses.
      - Ensure all names, dates, and amounts from User Data are integrated correctly.
    `;
    
    // 2. Generate Content
    const result = await model.generateContent(prompt);
    const htmlBody = result.response.text();

    // 2.5 Generate Evidence Hashing for Inventory
    const inventoryWithHashes = (formData.inventory || []).map(item => ({
      ...item,
      hash: generateHash(`${item.name}-${item.condition}-${Date.now()}`)
    }));

    const evidenceTable = inventoryWithHashes.length > 0 ? `
      <div class="annexure">
        <h3>Annexure III: Digital Certificate of Condition</h3>
        <p>The following items have been digitally recorded and hashed to prevent tampering. These hashes can be used to verify the original state of media files in case of a dispute.</p>
        <table>
          <thead>
            <tr><th>Item</th><th>Condition</th><th>SHA-256 Digital Fingerprint</th></tr>
          </thead>
          <tbody>
            ${inventoryWithHashes.map(i => `<tr><td>${i.name}</td><td>${i.condition}</td><td><code>${i.hash.substring(0, 16)}...</code></td></tr>`).join('')}
          </tbody>
        </table>
        <p style="font-size: 10pt; color: #666; margin-top: 20px;">* This certificate is generated by the SEBRI Infrastructure and is legally binding as evidence of property condition at the time of execution.</p>
      </div>
    ` : "";

    // 3. Render to PDF
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    
    // Inject legal stylesheet
    const styledHtml = `
      <html>
        <head>
          <style>
            body { font-family: "Times New Roman", Times, serif; padding: 40px; line-height: 1.6; font-size: 12pt; color: #000; }
            h1 { text-align: center; text-decoration: underline; margin-bottom: 20px; font-size: 18pt; }
            h3 { font-size: 13pt; margin-top: 15px; text-transform: uppercase; border-bottom: 1px solid #eee; }
            p { margin-bottom: 8px; text-align: justify; }
            .signature-block { margin-top: 40px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
            .sign-line { border-top: 1px solid black; margin-top: 40px; padding-top: 5px; }
          </style>
        </head>
        <body>
          ${htmlBody}
          ${evidenceTable}
        </body>
      </html>
    `;

    await page.setContent(styledHtml);
    const pdf = await page.pdf({ 
      format: 'A4', 
      printBackground: true,
      margin: { top: '1in', bottom: '1in', left: '1in', right: '1in' }
    });
    
    await browser.close();

    res.contentType("application/pdf");
    res.send(pdf);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate agreement' });
  }
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
